stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
    outs:
      - data/train.csv
      - data/test.csv

  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - data/train.csv
      - data/test.csv
    outs:
      - data/preprocessed_data.csv

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
      - src/feature_engineering.py
      - data/preprocessed_data.csv
    outs:
      - data/feature_engineering.csv

  model_training:
    cmd: python src/model_training.py
    deps:
      - src/model_training.py
      - data/feature_engineering.csv
    outs:
      - data/model_training.csv
      - data/X_test.csv
      - data/y_test.csv
      - models/Logistic Regression.pkl
      - models/Gradient Boosting.pkl
      - models/Histogram Gradient Boosting.pkl
      - models/Random Forest.pkl

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
      - src/model_evaluation.py
      - data/X_test.csv
      - data/y_test.csv
      - models/Logistic Regression.pkl
      - models/Gradient Boosting.pkl
      - models/Histogram Gradient Boosting.pkl
      - models/Random Forest.pkl
    outs:
      - report/metrics.json
