stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    outs:
    - data/train.csv
    - data/test.csv

  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - src/data_preprocessing.py
    - data/train.csv
    - data/test.csv
    outs:
    - data/preprocessed_data.csv

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
    - src/feature_engineering.py
    - data/preprocessed_data.csv
    outs:
    - data/feature_engineering.csv

  model_training:
    cmd: python src/model_training.py
    deps:
    - src/model_training.py
    - data/feature_engineering.csv
    outs:
    - data/model_training.csv
    - data/X_test.csv
    - data/y_test.csv
    - models/logistic_regression.pkl
    - models/gradient_boosting.pkl
    - models/histogram_gradient_boosting.pkl
    - models/random_forest.pkl
    params:
    - params.yaml:
      - model_training.test_size
      - model_training.random_state
      - model_training.logistic_regression
      - model_training.gradient_boosting
      - model_training.histogram_gradient_boosting
      - model_training.random_forest

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - src/model_evaluation.py
    - data/X_test.csv
    - data/y_test.csv
    - models/logistic_regression.pkl
    - models/gradient_boosting.pkl
    - models/histogram_gradient_boosting.pkl
    - models/random_forest.pkl
    outs:
    - report/metrics.json

metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
params:
- dvclive/params.yaml
