model_training:
  test_size: 0.21
  random_state: 42
  logistic_regression:
    C: 1.0
    max_iter: 100
  gradient_boosting:
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 3
  histogram_gradient_boosting:
    max_iter: 100
    learning_rate: 0.1
    max_depth: 3
  random_forest:
    n_estimators: 100
    max_depth: 3
    random_state: 42
data_paths:
  input_csv: data/feature_engineering.csv
  output_csv: data/model_training.csv
  x_test_csv: data/X_test.csv
  y_test_csv: data/y_test.csv
  model_dir: models
